USE [master]
GO

/****** Object:  Database [Central]    Script Date: 19/01/2015 09:33:41 p.m. ******/
CREATE DATABASE [Central]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Central', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Central.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Central_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Central_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Central] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Central].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Central] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Central] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Central] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Central] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Central] SET ARITHABORT OFF 
GO

ALTER DATABASE [Central] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Central] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Central] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Central] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Central] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Central] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Central] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Central] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Central] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Central] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Central] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Central] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Central] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Central] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Central] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Central] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Central] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Central] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Central] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Central] SET  MULTI_USER 
GO

ALTER DATABASE [Central] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Central] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Central] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Central] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Central] SET  READ_WRITE 
GO


